In [14]:
from datetime import datetime
from zoneinfo import ZoneInfo
import torch

In [13]:
now = datetime.now(ZoneInfo("America/Los_Angeles"))
now.strftime("%Y-%m-%d-%H-%M-%S-%s")

'2026-06-29-06-43-55-1782740635'

In [30]:

p = torch.tensor([
    [0.0, 0.2, 0.5, 0.78, 0.99, 1.0],
    [0.0, 0.2, 0.5, 0.78, 0.99, 1.0]
])

In [33]:
pp = torch.cumsum(p, dim=-1)
pp

tensor([[0.0000, 0.2000, 0.7000, 1.4800, 2.4700, 3.4700],
        [0.0000, 0.2000, 0.7000, 1.4800, 2.4700, 3.4700]])

In [ ]:
# torch.bucketize(torch.tensor([0.5, 0.9])[:, None], pp, out_int32=True).item()


RuntimeError: boundaries tensor must be 1 dimension, but got dim(2)

In [49]:
def bucketize(query_1d: torch.Tensor, boundaries_2d: torch.Tensor) -> torch.Tensor:
    # query is of size 1xb, boundaries of size b x vocab
    # result will be 1xb, one index from boundaries for each
    m = (query_1d <= boundaries_2d) * 1 #b x vocab
    # print(query_1d)
    # print(boundaries_2d)
    # print(m)

    return boundaries_2d.shape[-1] - torch.sum(m, dim=-1)


In [50]:
bucketize(torch.tensor([0.5, 0.9])[:, None], pp)

tensor([2, 3])

In [46]:
torch.rand(pp.shape[0])

tensor([0.3330, 0.4057])